Update nginx init script
Possible fix for nginx crash with epoll_wait() failed (4: Interrupted system call)

diff --git a/apachebooster/conf/nginx b/apachebooster/conf/nginx
--- a/apachebooster/conf/nginx
+++ b/apachebooster/conf/nginx
@@ -1,164 +1,140 @@
-#!/bin/bash
+#!/bin/sh
 #
-# nginx – this script starts and stops the nginx daemin
-# Taken from http://www.hikaro.com
-# chkconfig:   – 85 15
-# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
-#               proxy and IMAP/POP3 proxy server
+# nginx        Startup script for nginx
+#
+# chkconfig: - 85 15
 # processname: nginx
-# config:      /usr/local/nginx/conf/nginx.conf
-# pidfile:     /usr/local/nginx/logs/nginx.pid
+# config: /usr/local/nginx/conf/nginx.conf
+# pidfile: /usr/local/nginx/logs/nginx.pid
+# description: nginx is an HTTP and reverse proxy server
+#
+### BEGIN INIT INFO
+# Provides: nginx
+# Required-Start: $local_fs $remote_fs $network
+# Required-Stop: $local_fs $remote_fs $network
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: start and stop nginx
+### END INIT INFO
+
+ulimit -n 65535
 
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-# Source networking configuration.
-. /etc/sysconfig/network
+if [ -f /etc/sysconfig/nginx ]; then
+    . /etc/sysconfig/nginx
+fi
 
-# Check that networking is up.
-[ "$NETWORKING" = "no" ] && exit 0
-
-ulimit -n 32768
-nginx="/usr/local/nginx/sbin/nginx"
-prog=$(basename $nginx)
-
-NGINX_CONF_FILE="/usr/local/nginx/conf/nginx.conf"
-
-lockfile=/var/lock/subsys/nginx
+prog=nginx
+nginx=${NGINX-/usr/local/nginx/sbin/nginx}
+conffile=${CONFFILE-/usr/local/nginx/conf/nginx.conf}
+lockfile=${LOCKFILE-/var/lock/subsys/nginx}
+pidfile=${PIDFILE-/usr/local/nginx/logs/nginx.pid}
+SLEEPMSEC=100000
+RETVAL=0
 
 start() {
-[ -x $nginx ] || exit 5
-[ -f $NGINX_CONF_FILE ] || exit 6
-echo -n $"Starting $prog: "
-daemon $nginx -c $NGINX_CONF_FILE
-retval=$?
-echo
-[ $retval -eq 0 ] && touch $lockfile
-return $retval
-}
-fullstatus() {
-PIDFILE="/usr/local/nginx/logs/nginx.pid"
-STATUS="http://127.0.0.1/nginx_status"
-NOW=`date +%s`
-NGINX_START=`stat -c %Y $PIDFILE`
-if [ -z "$NGINX_START" ]; then
-        echo "Can't find nginx's pid file."
-        exit 1
-fi
-STAT=`curl -s $STATUS`
-OLDIFS="$IFS"
-IFS=$'\n'
-STAT=($STAT)
-if [[ ! "${STAT[0]}" =~ "Active connections" ]]; then
-        echo "Failed to curl status URL: $STATUS"
-        exit 1
-fi
-IFS=$' '
-SUMM=(${STAT[2]})
-REQUESTS=${SUMM[2]}
-CON_ACCEPTED=${SUMM[0]}
-CON_HANDLED=${SUMM[1]}
-IFS="$OLDIFS"
-ACTIVE=${STAT[0]}
-CURRENT=${STAT[3]}
-DURATION=$((NOW - $NGINX_START))
-if [ "$DURATION" -gt "86399" ]; then
-        UPTIME="`echo $DURATION | awk '{ printf("%.1f", $1 / 86400) }'` days"
-elif [ "$DURATION" -gt "3599" ]; then
-        UPTIME="`echo $DURATION | awk '{ printf("%.1f", $1 / 3600) }'` hours"
-else
-        UPTIME="`echo $DURATION | awk '{ printf("%.0f", $1 / 60) }'` minutes"
-fi
-REQPERCON=`echo $REQUESTS $CON_HANDLED | awk '{ printf("%.1f", $1 / $2) }'`
-REQPERSEC=`echo $REQUESTS $DURATION | awk '{ printf("%.1f", $1 / $2) }'`
-# Pad strings
-PLEN=%$((${#REQUESTS}))s
-CON_ACCEPTED=`printf "$PLEN" $CON_ACCEPTED`
-CON_HANDLED=`printf "$PLEN" $CON_HANDLED`
-echo "
-Nginx up $UPTIME
+    echo -n $"Starting $prog: "
 
-$ACTIVE
-$CURRENT
-
-Connections Accepted: $CON_ACCEPTED
- Connections Handled: $CON_HANDLED
-      Total Requests: $REQUESTS
-
- Requests/Connection: $REQPERCON
-     Requests/Second: $REQPERSEC
-"
-exit 0
+    daemon --pidfile=${pidfile} ${nginx} -c ${conffile}
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && touch ${lockfile}
+    return $RETVAL
 }
 
 stop() {
-echo -n $"Stopping $prog: "
-killproc $prog -QUIT
-retval=$?
-echo
-[ $retval -eq 0 ] && rm -f $lockfile
-return $retval
-}
-
-restart() {
-configtest || return $?
-stop
-start
+    echo -n $"Stopping $prog: "
+    killproc -p ${pidfile} ${prog}
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
 }
 
 reload() {
-configtest || return $?
-echo -n $"Reloading $prog: "
-killproc $nginx -HUP
-RETVAL=$?
-echo
+    echo -n $"Reloading $prog: "
+    killproc -p ${pidfile} ${prog} -HUP
+    RETVAL=$?
+    echo
 }
 
-force_reload() {
-restart
+upgrade() {
+    oldbinpidfile=${pidfile}.oldbin
+
+    configtest -q || return 6
+    echo -n $"Staring new master $prog: "
+    killproc -p ${pidfile} ${prog} -USR2
+    RETVAL=$?
+    echo
+    /bin/usleep $SLEEPMSEC
+    if [ -f ${oldbinpidfile} -a -f ${pidfile} ]; then
+        echo -n $"Graceful shutdown of old $prog: "
+        killproc -p ${oldbinpidfile} ${prog} -QUIT
+        RETVAL=$?
+        echo
+    else
+        echo $"Upgrade failed!"
+        return 1
+    fi
 }
 
 configtest() {
-$nginx -t -c $NGINX_CONF_FILE
+    if [ "$#" -ne 0 ] ; then
+        case "$1" in
+            -q)
+                FLAG=$1
+                ;;
+            *)
+                ;;
+        esac
+        shift
+    fi
+    ${nginx} -t -c ${conffile} $FLAG
+    RETVAL=$?
+    return $RETVAL
 }
 
 rh_status() {
-status $prog
+    status -p ${pidfile} ${nginx}
 }
 
-rh_status_q() {
-rh_status >/dev/null 2>&1
-}
-
+# See how we were called.
 case "$1" in
-start)
-rh_status_q && exit 0
-$1
-;;
-stop)
-rh_status_q || exit 0
-$1
-;;
-restart|configtest)
-$1
-;;
-reload)
-rh_status_q || exit 7
-$1
-;;
-force-reload)
-force_reload
-;;
-fullstatus)
-fullstatus
-;;
-status)
-rh_status
-;;
-condrestart|try-restart)
-rh_status_q || exit 0
-;;
-*)
-echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest|fullstatus}"
-exit 2
+    start)
+        rh_status >/dev/null 2>&1 && exit 0
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    status)
+        rh_status
+        RETVAL=$?
+        ;;
+    restart)
+        configtest -q || exit $RETVAL
+        stop
+        start
+        ;;
+    upgrade)
+        upgrade
+        ;;
+    condrestart|try-restart)
+        if rh_status >/dev/null 2>&1; then
+            stop
+            start
+        fi
+        ;;
+    force-reload|reload)
+        reload
+        ;;
+    configtest)
+        configtest
+        ;;
+    *)
+        echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
+        RETVAL=2
 esac
+
+exit $RETVAL
